### ISSUE TITLE
Refresh visuals without losing filter

### ISSUE THREAD

**Issue by YuriGal** [awslabs/amazon-quicksight-embedding-sdk#109] opened 2022-01-29 01:12 UTC
In our scenario some data has been updated at the data source side. In our app I can call `setParameters()` from client JS with some dummy parameter name - this will cause visuals to refresh and display new data.

The problem with this approach - if any filters were applied to the visuals, the above update will reset filters. So the question is: is it possible to refresh visuals from client-side code without losing filters?

**Comment by zzhengyi-amazon** [comment] 2022-03-30 16:46
Hello, 

Are you using StatePersistence in API call?
 [StatePersistenceEnabled](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GetDashboardEmbedUrl.html#API_GetDashboardEmbedUrl_RequestSyntax)? 

If you are using it, could you contact AWS Support and cut a tt to QuickSight Embedding team? We will need some more information to investigate. Thanks.

**Comment by YuriGal** [comment] 2022-03-31 13:25
Hi @zzhengyi-amazon, we did have a case with AWS support (ID 9547615031), last activity there - we were told that QS team will be looking into this, and then the case was closed due to inactivity and marked as resolved (which it isn't).

**Comment by Dhairyasarous** [comment] 2022-05-09 07:44
Hey, can you specify whether you are using state-persistence? I would recommend opening another case and adding the case id here so we can track it.

**Comment by Dhairyasarous** [comment] 2022-07-14 23:16
We have deployed the fix internally. Can you verify whether the issue is fixed on your end?

**Comment by YuriGal** [comment] 2022-07-15 12:20
@Dhairyasarous thanks! Will try this later today and get back with the results.

**Comment by YuriGal** [comment] 2022-07-19 15:16
@Dhairyasarous Tried it on our side again, and the issue is still happening. Basically when the data in the backed is updated - we call from the client side something like 
```
 embeddedSession.setParameters({ dummy: Math.random() });
```
Visuals are indeed updated, but, as before - all set filters are lost. Do we need to do something else on our side?

**Comment by sonals-amazon** [comment] 2022-08-11 07:53
We are not able to reproduce this issue internally. Setting a parameter does not change the filters or controls on a dashboard that are not dependent on the parameter. But any filter that depends on the parameter/uses the parameter value will be changed. This is by design.

If you can explain what you mean by "all set filters are lost" that will help us understand the issue a little better.

**Comment by YuriGal** [comment] 2022-08-11 11:05
Prerequisite: All visuals' datasets are based on direct queries to Postgres DB, not SPICE. Scenario is:
 
1. Two visuals are loaded - a chart and a grid
2. User clicks on a chart series - which acts as a filter for the grid - grid shows fewer records now.
3. External code updates data for one of the grid rows directly in the backend database
4. External code calls `setParameters()` on the embedded dashboard with a dummy parameter name and random data
5. Visuals refresh, but the filter that was set by the chart is reset - and grid once again shows full set of records.

Hopefully this makes sense, but please let me know if further clarification is needed.

**Comment by sonals-amazon** [comment] 2022-08-12 20:59
@YuriGal Could you please open an issue with the support so that we can understand this better. We did see a similar ticket in the past but that was closed in misunderstanding.

**Comment by bwelkin** [comment] 2023-03-14 16:02
Resolving this issue as it is not within `amazon-quicksight-embedding-sdk` package's functionality. Issue is within the iframe. The QuickSight team will look into this.

**Closed by bwelkin** 2023-03-14 16:02 UTC
