### ISSUE TITLE
Print button disappears in embedded dashboards

### ISSUE THREAD

**Issue by bernhardboehm** [awslabs/amazon-quicksight-embedding-sdk#122] opened 2022-07-14 07:24 UTC
We are embedding Quicksight dashboards into our application and all of a sudden the Print button (as well as the Undo/Redo buttons) started to only appear on the first dashboard view but when navigating to another dashboard using dashboard.navigateToDashboard(options); it disappears. The behaviour is the same regardless of which dashboard I view first. 
Does anybody experience the same or maybe even have a solution?

**Comment by jcardus** [comment] 2022-08-04 17:20
Yes, same here!

**Comment by bwelkin** [comment] 2022-08-12 18:07
Thank you for reporting the issue. We are working on it and will update the thread once we have a fix.

**Comment by bernhardboehm** [comment] 2022-09-20 06:51
Hello Brian, is there any news on this issue with the print button?

**Comment by sonals-amazon** [comment] 2022-09-30 20:57
Duplicate of https://github.com/awslabs/amazon-quicksight-embedding-sdk/issues/125 

Tracking in the other github issue and closing this one.

**Closed by sonals-amazon** 2022-09-30 20:57 UTC
