### ISSUE TITLE
Locale-Option does not have any effect on number formats

### ISSUE THREAD

**Issue by d-koppenhagen** [awslabs/amazon-quicksight-embedding-sdk#142] opened 2023-03-21 21:53 UTC
When setting the locale using the SDK, I expected that KPIs are formatted for the target locale.
For example the Number `12345678` is formatted as `12,345,678` by default (`en-US`). When passing `de-DE` I expect the output to be `12.345.678`. It seems the value isn't evaluated.
The locale Option is set by the SDK in the iframes `src`. So probably the error is within Quicksight itself but not the SDK?

I also tries out other common locale formats like: `de`, `DE`, `de_DE`. All are not leading to the expected result.

**Comment by bwelkin** [comment] 2023-03-21 22:29
I tested `de-DE` locale with the SDK, and content changed into German language. Do you see some content in German? If so, the issue is not in SDK as you suggested. Please contact [AWS Customer Support](https://aws.amazon.com/contact-us/) so that a ticket can be created and assigned to the QuickSight team that handles the localizations.

**Comment by bwelkin** [comment] 2023-03-21 22:55
For reference, the expected locale values are listed at https://github.com/awslabs/amazon-quicksight-embedding-sdk#-locale-string-optional-not-available-in-qsearchbar-embedding

**Comment by d-koppenhagen** [comment] 2023-03-22 06:57
@bwelkin can you share the example where you tested it? Do I have to configured something within QS to respect the locale as a parameter?

I just tried to set the locale on some of the [Quicksight Dashboards available in the Gallery](https://aws.amazon.com/de/quicksight/gallery/).

It doesn't matter what locale I set, the result stay always the same (independent from using the SDK):

- https://d2lzvqq4w5ulk4.cloudfront.net/?dashboardName=finance&locale=en-US
- https://d2lzvqq4w5ulk4.cloudfront.net/?dashboardName=finance&locale=de-DE
- https://d2lzvqq4w5ulk4.cloudfront.net/?dashboardName=finance&locale=fr-FR

Also I tried to open the URLs above in incognito windows, but nothing changed.

So I am just wondering why it works on your site?

**Comment by bwelkin** [comment] 2023-03-22 10:58
You are adding the locale on the top page url. The locale on the iframe still remains `en-US`. Try executing
```
document.querySelector('iframe').src = document.querySelector('iframe').src.replace('en-US', 'de-DE')
```
on the console.

**Comment by bwelkin** [comment] 2023-03-22 11:13
The example below should be adding a `locale` query string parameter on the `src` of the `iframe` it creates inside the  `<YOUR_CONTAINER>` element:
```
const embeddingContext = await createEmbeddingContext();
const embeddedDashboardExperience = await embeddingContext.embedDashboard({
    url: '<YOUR_EMBED_URL>',
    container: '<YOUR_CONTAINER>',
},{
    locale: 'de-DE'
});
```

**Comment by d-koppenhagen** [comment] 2023-03-22 12:20
Okay, that's exactly how i configured it. And the iframe in my project shows `de-DE` already.
But I think the problem isn't located in the SDK as I can confirm, some things like the `Fund Type` in the example above is indeed changing. I was always focussed on how the numbers (KPI)s are displayed. It seems like the locale is ignored for this values as here I would expect to see `28.982` instead of `28,982` and `5,57` instead of `5.57` when calling it with a German locale set to `de-DE`.
So I have to contact the Customer Support as you suggested.
Thanks for your help!

**Closed** 2023-03-22 12:22 UTC
