### ISSUE TITLE
navigateToDashboard not accepting parameters

### ISSUE THREAD

**Issue by abhisheksett** [awslabs/amazon-quicksight-embedding-sdk#80] opened 2021-05-26 13:15 UTC
I'm trying to use navigateToDashboard method and my code looks like this:

```
embedDashboard.navigateToDashboard({
   dashboardId,
   parameters: {
      startDate,
      endDate
   }
});
```

However, I'm always getting the following error:

```
embed-dashboard.bundle.7c5390c5f709b1b11769.31.js:2 Uncaught TypeError: e[r].map is not a function
    at embed-dashboard.bundle.7c5390c5f709b1b11769.31.js:2
    at Array.forEach (<anonymous>)
    at e._constructHashString (embed-dashboard.bundle.7c5390c5f709b1b11769.31.js:2)
    at embed-dashboard.bundle.7c5390c5f709b1b11769.31.js:2
    at embedding.0e133f13518143eeb152.31.js:2
    at Set.forEach (<anonymous>)
    at y.e.trigger (embedding.0e133f13518143eeb152.31.js:2)
    at y.<anonymous> (embed-dashboard.bundle.7c5390c5f709b1b11769.31.js:2)
```

If I don't pass the parameters and only dashboard Id, it works properly

**Comment by chaudharivijay** [comment] 2021-06-02 04:05
As shown in sample (see below), parameters is a map.

```
    var options = {
        dashboardId: "37a99f75-8230-4409-ac52-e45c652cc21e",
        parameters: {
            country: [
                "United States"
            ]
        }
    };
    dashboard.navigateToDashboard(options);

```


Please change the input to 

```
embedDashboard.navigateToDashboard({
   dashboardId,
   parameters: {
      startDate: startDate,
      endDate: endDate
   }
});
```

assuming that "startDate" and "endDate" are the parameter names and `startDate` and `endDate` are the corresponding values.

**Comment by abhisheksett** [comment] 2021-06-03 11:06
@chaudharivijay I didn't get the difference between the code I have written and the one you shared. Yes, I used ES6 object shorthands. But could you please mention where is the difference?

**Comment by krishnatgkk123** [comment] 2021-06-09 09:41
Abhishek : were you able to find the solution. facing the same issue in my Angular application.

**Comment by abhisheksett** [comment] 2021-06-09 17:57
> @abhisheksett : were you able to find the solution. facing the same issue in my Angular application.

Nope didn't find any solution yet :( :(

**Comment by chaudharivijay** [comment] 2021-06-10 15:12
Hi,
We identified the cause and will push out a fix soon.

**Comment by abhisheksett** [comment] 2021-06-14 18:31
@chaudharivijay thanks a lot, this worked for the time being

**Comment by Dhairyasarous** [comment] 2021-07-14 19:28
We have deployed the fix internally. I have verified that the following also works now:

```
embedDashboard.navigateToDashboard({
   dashboardId,
   parameters: {
      startDate: startDate,
      endDate: endDate
   }
});
```

I am closing this issue.

**Closed by Dhairyasarous** 2021-07-14 19:28 UTC
