### ISSUE TITLE
Download in PDF doesn't get the filtered values

### ISSUE THREAD

**Issue by iamajvillalobos** [awslabs/amazon-quicksight-embedding-sdk#89] opened 2021-09-03 12:34 UTC
## Screenshot
![CleanShot 2021-09-03 at 20 31 04@2x](https://user-images.githubusercontent.com/7567758/132005754-9a43232c-adea-41b7-b4d1-330d06be0707.png)

## Description
I filter values using the dropdown, it drill downs the data but when I click the Download in PDF it doesn't get the filtered values. It works though when I do the `Print` button.

I already updated to the latest version of the js package. Any tips?

**Comment by zzhengyi-amazon** [comment] 2021-09-09 18:40
Thanks for bringing this to our attention. 
We could not reproduce it on our side. Could you contact AWS support to cut a ticket to QuickSight team with the information of the dashboard you are using, so that we could dive deep.
Thanks.

**Comment by davidwhand** [comment] 2022-01-17 11:58
We are having the same exact issue. Was there a resolution?

**Comment by zzhengyi-amazon** [comment] 2022-03-30 17:34
Hello,

QuickSight team has a fix for this issue. Could you validate if the issue fixed on your side?

Resolve this issue. Feel free to re-open it if you still see the issue. Thanks.

**Closed by zzhengyi-amazon** 2022-03-30 17:34 UTC
