### ISSUE TITLE
React native integration throws Unhandled promise rejection, [ReferenceError: Can't find variable: HTMLElement]

### ISSUE THREAD

**Issue by Shibu-N** [awslabs/amazon-quicksight-embedding-sdk#55] opened 2020-11-04 14:07 UTC
Tried integration for the react native integration throws error " Unhandled promise rejection, [ReferenceError: Can't find variable: HTMLElement] ". Is it like the package not supported for react-native? Below is the code that i've been trying. The same code works for the react when div is used instead of View.

`embedDashboard = (embeddedurl, containerDiv) => {
    var dashboard;
    var options = {
      url: embeddedurl,
      container: containerDiv,
      scrolling: 'no',
      height: '700px',
      width: '1200px',
      locale: 'en-US',
      footerPaddingEnabled: true
    };
    dashboard = QuickSightEmbedding.embedDashboard(options);
    dashboard.on('error', this.onError);
    dashboard.on('load', this.onDashboardLoad);
  };
componentDidMount() {
  this.embedDashboard(embeddedurl, this.dsr.current);
}

render(){
 return(
<View ref={this.dsr} style={{ overflow: 'scroll', width: '100%' }}></View>
)
}
`

**Comment by Graig123git** [comment] 2020-12-05 08:38
@Shibu-N did you fine a work around for react native ?

**Comment by njacob1001** [comment] 2021-06-14 19:46
@Graig123git  Just use `react-native-webview` and insert the url of iframe :D it works for me

**Comment by tusharthinksys** [comment] 2021-08-03 17:32
@njacob1001 Please provide me code as you implemented to show graph(QuickSight).

**Comment by bwelkin** [comment] 2023-03-13 23:12
Closing as the issue is too old. Please create a new issue if you still encounter react native integration.

**Closed by bwelkin** 2023-03-13 23:12 UTC
